spring:
  application:
    name: demoNoSQL
#Data Source
  data:
    mongodb:
      #username: sa
      #password: Passw0rd
      host: localhost
      port: 27017
      database: express-test
      authentication-database: admin

#Log
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

