spring:
  application:
    name: springApi
  datasource:
    url: jdbc:postgresql://localhost:5432/ludothequeApi
    username: ludothequeApi
    password: password
  jpa:
    hibernate:
      ddl-auto: create